### PR TITLE
Use activeAfterCancel for 'Detect Language' consistently

### LINKED ISSUE #241: Detect Language fails for empty text
The interface doesn't catch attempts to detect the language of empty text which results in https://www.apertium.orf/apy/identifyLang producing code 400 errors.

screenshot

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #241 
@sushain97 Friendly ping.

### CODE REVIEW

**Comment by sushain97** [comment]
screenshots? it seems like your code hides instead of disabling.

check out what happens when I switch to website translation -- it should be similar

**Comment by Androbin** [comment]
Just noticed, this logic was already implemented but not triggered on load.

**Comment by sushain97** [comment]
Code looks alright. How does this mesh with the changes in https://github.com/goavki/apertium-html-tools/pull/239? Does it get updated correctly?

**Comment by Androbin** [comment]
We should probably make use of the `activeAfterCancel` class introduced.

**Comment by Androbin** [comment]
@sushain97 Are you okay with the lastest changes?

File: assets/js/translator.js [hunk 1]
```diff
@@ -29,6 +29,35 @@ var PUNCTUATION_KEY_CODES = [46, 33, 58, 63, 47, 45, 190, 171, 49]; // eslint-di
     callApy, apyRequestTimeout, isURL */
 /* global ENTER_KEY_CODE, HTTP_BAD_REQUEST_CODE, HTTP_OK_CODE, SPACE_KEY_CODE, XHR_DONE, XHR_LOADING */
 
+function updateDetect(state /*: bool */) {
```
Comment (sushain97) [inline assets/js/translator.js]: Could you move this function to a more appropriate location?

Comment (Androbin) [reply assets/js/translator.js]: In terms of module or what?

Comment (Androbin) [reply assets/js/translator.js]: What would be the alternative?

Comment (sushain97) [reply assets/js/translator.js]: Somewhere with the other functions? i.e. around L1026

**Comment by Androbin** [comment]
@sushain97 Are you satisfied with the PR?

File: assets/js/translator.js [hunk 2]
```diff
@@ -58,12 +58,10 @@ if(modeEnabled('translation')) {
             });
 
             $('#originalText').on('input propertychange', function () {
-                var disableDetect = this.value === '';
-                $('#detect, #srcLangSelect option[value="detect"]').prop('disabled', disableDetect);
-                $('#detect').toggleClass('disabledLang', disableDetect);
-
-                persistChoices('translator');
+                updateDetect($('#originalText').text() !== '');
```
Comment (sushain97) [inline assets/js/translator.js]: What would happen if this triggers with `false` here and then `true`? There's no `true` call corresponding to your `$('#detect, #srcLangSelect option[value="detect"]').prop('disabled', true);`.

Comment (Androbin) [reply assets/js/translator.js]: Interesting, none of the previous code did this properly.

**Comment by Androbin** [comment]
Okay, I know what you meant. Should be more logical now.

File: assets/js/translator.js [hunk 3]
```diff
@@ -1018,6 +994,36 @@ function showTranslateWebpageInterface(url /*: ?string */, ignoreIfEmpty /*: ?bo
...
 
+function updateDetect(state /*: bool */) {
+    var oldState;
+
+    if(state) {
+        oldState = $('#detect').hasClass('activeAfterCancel');
+
+        if(oldState) {
+            $('#detect').removeClass('activeAfterCancel');
+            $('#detect').click();
```
Comment (sushain97) [inline assets/js/translator.js]: This is problematic. Consider the following sequence of events:

1. I type some text in
2. I click detect (it detects Spanish)
3. I click website translation (it switches to Spanish in the recent languages NOT detect and disables the detect button)
4. I cancel website translation and go back to text translation

The current code would click the detect button and a new request would be sent to APy. The old code doesn't do that since we already know what the detected language is and don't need a new request, hence the call to `detectLanguageSuccess...` only.

Comment (Androbin) [reply assets/js/translator.js]: Okay, not I get it. Thanks for the explanation.

**Comment by Androbin** [comment]
Does this look okay now?

**Comment by Androbin** [comment]
How/Where does the input field get populated from the query string?

**Comment by Androbin** [comment]
Seems like the `inputchange` wasn't triggered...

**Comment by Androbin** [comment]
Okay, got it. I was testing `.text()` which is of course rubbish.
