### PR TITLE
Fix buggy UI with detect-language.

### LINKED ISSUE #236: Buggy UI after switching into translate document/webpage after detecting language
No language is selected anymore:

image

### PR DESCRIPTION
**Pull request by JPJPJPOPOP**
Fixes #236.

### CODE REVIEW

**Comment by shardulc** [comment]
@sushain97 Works perfectly fine for me. If selecting `srcLang1` by default is OK (when would it not be?), I think this can be merged.

File: assets/js/translator.js [hunk 1]
```diff
@@ -89,6 +89,13 @@ if(modeEnabled('translation')) {
                     $('div#translateText').fadeIn('fast', function () {
                         synchronizeTextareaHeights();
                     });
+                    if($('#detect').hasClass('originDetect') === true) {
+                        $('#srcLang1').removeClass('active');
```
Comment (sushain97) [inline assets/js/translator.js]: I think `.srcLang` would work here and below.

Comment (JPJPJPOPOP) [reply assets/js/translator.js]: @sushain97 ok, changing.

File: assets/js/translator.js [hunk 2]
```diff
@@ -111,6 +116,11 @@ if(modeEnabled('translation')) {
                     $('#fileInput').show();
                     $('div#fileName').hide();
                     $('div#docTranslation').fadeIn('fast');
+                    if($('#detect').hasClass('active') === true) {
+                        $('#srcLang1').addClass('active');
```
Comment (sushain97) [inline assets/js/translator.js]: I’m somewhat afraid of doing things in a more ad hoc manner like this because just changing the classes around might not change some of the program state that should also have been changed.

`$('#srcLang1').click()` might be better? and when switching back, do some of the things in `handleDetectLanguageSuccessResponse` if detect was selected?

Comment (JPJPJPOPOP) [reply assets/js/translator.js]: @sushain97
When you say "do some of the things in `handleDetectLanguageSuccessResponse` if detect was selected", do you mean move the stuff that is after $('#detect').hasClass('active') === true?
